# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://github.com/SeliMeli/osx-jetbrains-keymap-for-windows

name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
        working-directory: ./keymap-generator
      - run: npm test
        working-directory: ./keymap-generator

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: ./keymap-generator
      - run: npm publish
        working-directory: ./keymap-generator
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        working-directory: ./keymap-generator
      - run: npm publish
        working-directory: ./keymap-generator
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
